### ISSUE TITLE
MetaData: column order

### ISSUE THREAD

**Issue by DStrelak** [I2PC/xmippCore#128]
Currently, the vector version and the sql version of the metadata outputs columns in different order.
The vector data does so in the internal order of the metadata labels, while the sql version does so in the alphabetic order of the labels.

1. Should the order be fixed? If yes, in which way? Alphabetically, in the order of addition, in the label order ...?
2. Should we support column reordering?

In case of the alphabetic order, consider adding `LabelsOrderedByName()` or similar method to `metadata_label.h/cpp`

**Comment by slajo** [comment]
The meaning of (internal) "label order" is not clear to me. The best would be to have the columns written in the order of addition and, at the same time, establish a convention for the order of columns that are used the most often like the image/volume name, enabled, rot, tilt, psi, and shift_x, shift_y, shift_z (the order that we had earlier for these columns was quite good). It would be useful to allow reordering of columns with xsj.

**Comment by DStrelak** [comment]
Hi,
> The meaning of (internal) "label order" is not clear to me.

It's the order within the enum: https://github.com/I2PC/xmippCore/blob/devel/core/metadata_label.h#L44

> columns written in the order of addition and, at the same time, establish a convention for the order of columns that are used the most often

You mean that e.g. `enabled, rot, tilt, psi, and shift_x, shift_y, shift_z` would always be first and in this order and the rest would be in the order of insertion?


> It would be useful to allow reordering of columns with xsj.

Currently `xsj` allows for changing the order of the columns, however it does not save that information in the text file.

**Comment by slajo** [comment]
Hi,

> > The meaning of (internal) "label order" is not clear to me.
> 
> It's the order within the enum: https://github.com/I2PC/xmippCore/blob/devel/core/metadata_label.h#L44
> 

Now, I understand that the order of labels in enum is the one that appears in the metadata files, but this order is clearly not alphabetical (e.g., MDL_ANGLE_TILT_DIFF before MDL_ANGLE_DIFF0; MDL_ANGLE_PSI before MDL_ANGLE_DIFF0). So, I think it would be good to change the order of items in enum to make  "image, enabled, rot, tilt, psi, and shift_x, shift_y, shift_z" always be the first columns. Also, other items/labels could be reordered in this enum list in the way we all like them to appear.

> > columns written in the order of addition and, at the same time, establish a convention for the order of columns that are used the most often
> 
> You mean that e.g. `enabled, rot, tilt, psi, and shift_x, shift_y, shift_z` would always be first and in this order and the rest would be in the order of insertion?
> 

Yes, but including "image" before "enabled". The rest would depend on the order of insertion. 
However, it seems easy to reorder enum to make this order (image, enabled, rot, tilt, psi, and shift_x, shift_y, shift_z) the default one. We can perhaps also agree on the order of other columns in the enum list. In that case, the columns would appear in the order of internal labels (enum) but it would be the order we like to see.

> > It would be useful to allow reordering of columns with xsj.
> 
> Currently `xsj` allows for changing the order of the columns, however it does not save that information in the text file.

I think it could be an interesting feature to allow xsj save the reordered columns into a new metadata file.

**Comment by albertmena** [comment]
We considered this is not a bug.
