### ISSUE TITLE
New compile warnings

### ISSUE THREAD

**Issue by DStrelak** [I2PC/xmippCore#53]
Branch: python3_migration
Warnings: https://travis-ci.com/github/I2PC/xmipp/builds/161714136#L3547  (onwards)
Since: https://github.com/I2PC/xmippCore/commit/5d675e0e88da3f5f3e9f3874096af724a63ca6d7
How to reproduce: rebuild xmippCore (cuda must be on)

**Comment by cossorzano** [comment]
Solved, there is a PR
