### ISSUE TITLE
Hdf5 files stays locked after quering the dimensions though the python binding

### ISSUE THREAD

**Issue by pconesa** [I2PC/xmippCore#72]
Not sure if this is a problem of the binding or is deeper.

A way to reproduce it though scipion is:

````
scipion3 python
from pwem.emlib.image import ImageHandler
ih = ImageHandler()
ih.getDimensions("/home/pablo/ScipionUserData/projects/TestEmanInitialModelGroel/Runs/000074_EmanProtInitModel/extra/initial_models/model_00_10.hdf")
proc = psutil.Process(os.getpid())
proc.proc.open_files()
````

Prints: 

````
[popenfile(path='/home/pablo/ScipionUserData/projects/TestEmanInitialModelGroel/Runs/000074_EmanProtInitModel/extra/initial_models/model_00_10.hdf', fd=3, position=11200, mode='r', flags=32768)]
````
ih.getDimensions() ends up calling c++ Image for hrf5 files. I've tried other extensions (map, vol) and files are not locked :

````
                self._img.read(location, lib.HEADER)
                return self._img.getDimensions()
````

Maybe it needs a specific close call. But I haven't found this though the python binding

**Comment by DStrelak** [comment]
I suggest to drop support of hdf5 :D
Devel branch?
Can you send me the file?

**Comment by pconesa** [comment]
I'm working on release-20.07 but I guess it will happen in devel too

Any hdf file should be ok, try any of these: http://scipion.cnb.csic.es/downloads/scipion/data/tests/eman/mics/

**Comment by DStrelak** [comment]
> I'm working on release-20.07 but I guess it will happen in devel too

Does it have to be fixed in release?

**Comment by pconesa** [comment]
Only if solucion dosn't risk anything I'd say. Otherwise we can live with it.....It's been like this since the beginning I think
